/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sadgames_gl3dengine_glrender_GLES20JniWrapper */

#ifndef _Included_com_sadgames_gl3dengine_glrender_GLES20JniWrapper
#define _Included_com_sadgames_gl3dengine_glrender_GLES20JniWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sadgames_gl3dengine_glrender_GLES20JniWrapper
 * Method:    glClear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sadgames_gl3dengine_glrender_GLES20JniWrapper_glClear
  (JNIEnv *, jclass);

/*
 * Class:     com_sadgames_gl3dengine_glrender_GLES20JniWrapper
 * Method:    glClearColor
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_com_sadgames_gl3dengine_glrender_GLES20JniWrapper_glClearColor
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_sadgames_gl3dengine_glrender_GLES20JniWrapper
 * Method:    glViewport
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_sadgames_gl3dengine_glrender_GLES20JniWrapper_glViewport
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_sadgames_gl3dengine_glrender_GLES20JniWrapper
 * Method:    glExtensions
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sadgames_gl3dengine_glrender_GLES20JniWrapper_glExtensions
  (JNIEnv *, jclass);

/*
 * Class:     com_sadgames_gl3dengine_glrender_GLES20JniWrapper
 * Method:    glUseProgram
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_sadgames_gl3dengine_glrender_GLES20JniWrapper_glUseProgram
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_sadgames_gl3dengine_glrender_GLES20JniWrapper
 * Method:    glEnableFrontFacesCulling
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sadgames_gl3dengine_glrender_GLES20JniWrapper_glEnableFrontFacesCulling
  (JNIEnv *, jclass);

/*
 * Class:     com_sadgames_gl3dengine_glrender_GLES20JniWrapper
 * Method:    glEnableBackFacesCulling
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sadgames_gl3dengine_glrender_GLES20JniWrapper_glEnableBackFacesCulling
  (JNIEnv *, jclass);

/*
 * Class:     com_sadgames_gl3dengine_glrender_GLES20JniWrapper
 * Method:    glEnableFacesCulling
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sadgames_gl3dengine_glrender_GLES20JniWrapper_glEnableFacesCulling
  (JNIEnv *, jclass);

/*
 * Class:     com_sadgames_gl3dengine_glrender_GLES20JniWrapper
 * Method:    glEnableDepthTest
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sadgames_gl3dengine_glrender_GLES20JniWrapper_glEnableDepthTest
  (JNIEnv *, jclass);

/*
 * Class:     com_sadgames_gl3dengine_glrender_GLES20JniWrapper
 * Method:    glBindFramebuffer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_sadgames_gl3dengine_glrender_GLES20JniWrapper_glBindFramebuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_sadgames_gl3dengine_glrender_GLES20JniWrapper
 * Method:    glCheckFramebufferStatus
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_sadgames_gl3dengine_glrender_GLES20JniWrapper_glCheckFramebufferStatus
  (JNIEnv *, jclass);

/*
 * Class:     com_sadgames_gl3dengine_glrender_GLES20JniWrapper
 * Method:    glFramebufferAttachDepthTexture
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_sadgames_gl3dengine_glrender_GLES20JniWrapper_glFramebufferAttachDepthTexture
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_sadgames_gl3dengine_glrender_GLES20JniWrapper
 * Method:    glFramebufferAttachColorTexture
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_sadgames_gl3dengine_glrender_GLES20JniWrapper_glFramebufferAttachColorTexture
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
