/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sadgames_sysutils_common_RG_ETC1_JniWrapper */

#ifndef _Included_com_sadgames_sysutils_common_RG_ETC1_JniWrapper
#define _Included_com_sadgames_sysutils_common_RG_ETC1_JniWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sadgames_sysutils_common_RG_ETC1_JniWrapper
 * Method:    packETC1BlockInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sadgames_sysutils_common_RG_1ETC1_1JniWrapper_packETC1BlockInit
  (JNIEnv *, jclass);

/*
 * Class:     com_sadgames_sysutils_common_RG_ETC1_JniWrapper
 * Method:    packETC1Block
 * Signature: ([I[I)I
 */
JNIEXPORT jint JNICALL Java_com_sadgames_sysutils_common_RG_1ETC1_1JniWrapper_packETC1Block
  (JNIEnv *, jclass, jintArray, jintArray);

/*
 * Class:     com_sadgames_sysutils_common_RG_ETC1_JniWrapper
 * Method:    unpackETC1Block
 * Signature: ([I[I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_sadgames_sysutils_common_RG_1ETC1_1JniWrapper_unpackETC1Block
  (JNIEnv *, jclass, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
